#!/bin/bash


usage () {
    echo
    echo "$0 <COMMIT or FILE>"
    echo
    cat <<EOF
    This will guess if a commit is in a given Ubuntu kernel or not
    by passing the script either a file with a list of COMMIT IDs ONLY
    with one commit per line, OR passing it a single commit ID.
    This will give you the first kernel that a given commit appeared
    and thus the kernel returned may be far earlier than you are
    expecting, especially in the case of mainline where the first
    kernel version may be an interim staging version.

    This is meant to be run against Ubuntu kernel trees only, though
    it will attempt to guess an upstream kernel IF you have added a mainline
    kernel tree as a remote:

      git remote add <NAME> <URL>

    It cannot tell you which remote provided the tag, so if you have multiple
    remotes as I sometimes do (mainline, torvalds, scsi-staging, linux-next)
    the tag could come from any one of them but it will at least get you a
    starting point for further searching.

    When passing a file to the script, the file MUST BE in the format of a list
    of commit IDs only, no summary or other data, one commit per line.
EOF
}

if [ "$#" -ne "1" ]; then
    usage
    exit 1
fi

print_result() {
    echo "$1" |tee -a patch-check.log
}

check_ubuntu() {
    commit=$(echo "$1" |awk '{print $1}')
    commit_summary=$(git log --oneline --ignore-missing "$commit" 2>/dev/null|head -1)    
    if [ ! -z "$commit_summary" ]; then
        kernel=$(git describe --match "Ubuntu-[0-9]*" --contains "$commit" 2>/dev/null)
        if [ -z "$kernel" ]; then    
            # Sometimes the commit we're looking for is already pulled in via a
            # different commit, this (hopefully) finds that new commit.
            # Does commit exist in the logs?
            kernel=$(git describe --contains "$commit" 2>/dev/null)
            if [ -z "$kernel" ]; then
                return 1
            else
                print_result "$commit missing in Ubuntu, found upstream at $kernel"
                return 0
            fi
        else
            print_result "$commit exists in Ubuntu starting at $kernel"
            return 0
        fi
    fi
    # Not found in Ubuntu, return false so we can check upstream.
    return 1
}


check_upstream () {
    commit="$1"
    #if [ -z "$commit" ]; then
        realcommit=$(git log --oneline --grep="$commit"|awk '{print $1}')
        if [ ! -z "$realcommit" ]; then
            kernel=$(git describe --contains "$realcommit")
            print_result "$commit is provided by $realcommit in Ubuntu starting at $kernel"
        else
            # Anything that hits this is not in Ubuntu, BUT if you have also set up
            # a mainline remote and fetched it's refs, it will attempt to tell you
            # where in mainline it first appeared as well.
            #kernel=$(git tag --contains $1 'v*'|head -1 || git describe --contains $1)
            kernel=$(git tag --contains "$commit" 'v*' 2>&1 |head -1|| git describe --contains "$commit" 2>&1)
            shopt -s nocasematch
            if [[ "$kernel" =~ .*"Could not get".* ]] || [[ "$kernel" =~ .*"error: malformed object".* ]]; then
                print_result "$commit does not appear in either ubuntu or the upstream kernel."
            else 
                #kernel="$kernel merged on $(git log "$commit" |head -3 |grep Date|cut -f 1 -d ' ' --complement|sed -e 's/^[ \t]*//')"
                print_result "$commit missing in Ubuntu. Best guess on first appearance upstream: $kernel"
            fi
            shopt -u nocasematch
        fi
    #fi
}

if [ -f $1 ]; then
    for commit in $(cat $1|awk '{print $1}'); do
        if ! check_ubuntu "$commit"; then
            check_upstream "$commit"
        fi
    done
else
    if ! check_ubuntu "$1"; then
        check_upstream "$1"
    fi
fi
