#!/bin/bash

LOGSDIR=~/testflinger-console-logs
JOBFILE="job-ids"

print_job_status() {
    while read -r line; do
        id=$(echo $line | awk '{print $1}')
        ts=$(echo $line | awk '{print $3}' | sed 's/.$//')
        name=$(echo $line | awk '{print $4" "$5}')
        prompt="$id $ts $name"
        status=$(testflinger status $id 2>/dev/null)
        echo "$prompt: $status"
    done <$LOGSDIR/$JOBFILE
}

cancel_all_jobs() {
    while read -r line; do
        id=$(echo $line | awk '{print $1}')
        testflinger cancel $id
    done <$LOGSDIR/$JOBFILE
}

process_jobs() {
    while read -r line; do
        id=$(echo $line | awk '{print $1}')
        ts=$(echo $line | awk '{print $3}' | sed 's/.$//')
        name=$(echo $line | awk '{print $4" "$5}')
        prompt="$id $ts $name"
        status=$(testflinger status $id 2>/dev/null)
        case $status in
            cancelled)
                echo "$prompt: $status - Deleting"
                sed -i "/$id/d" $LOGSDIR/$JOBFILE
                ;;
            "")
                echo "$prompt: Not Found, deleting"
                sed -i "/$id/d" $LOGSDIR/$JOBFILE
                ;;
            *)
                echo "$prompt: $status"
        esac
    done <$LOGSDIR/$JOBFILE
}

get_results() {

}

# Main script execution
case "$1" in
    --cancel-all)
        cancel_all_jobs
        ;;
    --status-only)
        print_job_status
        ;;
    *)
        process_jobs
        ;;
esac

