#!/bin/bash

LOGSDIR=~/testflinger-console-logs
JOBFILE="job-ids"

cancel_all_jobs() {
    while read -r line
    do
        id=`echo $line |awk '{print $1}'`
        testflinger cancel $id
    done <$LOGSDIR/$JOBFILE
}

# Check if the first argument is --cancel-all and then cancel all jobs
if [ "$1" == "--cancel-all" ]; then
    cancel_all_jobs
    exit 0
fi

while read -r line
do
    id=`echo $line |awk '{print $1}'`
    ts=`echo $line |awk '{print $3}'|sed 's/.$//'`
    name=`echo $line |awk '{print $4" "$5}'`
    prompt="$id $ts $name"
    status=$(testflinger status $id 2>/dev/null)
    case $status in
    cancelled)
	    echo "$prompt: $status - Deleting"
            sed -i "/$id/d" $LOGSDIR/$JOBFILE
	    ;;
	"")
	    echo "$prompt: Not Found, deleting"
            sed -i "/$id/d" $LOGSDIR/$JOBFILE
	    ;;
	*)
	    echo "$prompt: $status"
    esac  
	    
done <$LOGSDIR/$JOBFILE
