#!/bin/bash

## create a new git branch on the latest Master using specified or requested
#branch name.

# make sure we're in master
git checkout master

if [[ $? -ne 0 ]]; then
    echo "ERROR: This may not be a git branch..."
    exit 1
fi

# make sure we're up to date
git fetch origin master
git pull origin master

# if we haven't specified a new branch, then ask for it now
if [[ $# -lt 1 ]]; then
    read -p "Enter branch name: " branch_name
    echo ""
else
    branch_name=$1
fi

git checkout -b $branch_name
git status

echo "Now ready to start hacking!"
